// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nykjyfmcajclesqwtthf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55a2p5Zm1jYWpjbGVzcXd0dGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzc1NTcsImV4cCI6MjA1OTcxMzU1N30.Ywn29WyKhyX3k-8Q8Lmg8aH56wlnr3B8pp74iGc0GLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);